services:
  postgres_pr:
    container_name: hackathon_mes_postgres
    image: postgres:17.6
    restart: unless-stopped
    env_file:
      - src/app/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      TZ: Europe/Moscow
    ports:
      - "5450:5432"
    volumes:
      - hackathon_SL_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    container_name: hackathon_mes_backend
    build:
      context: src
    restart: unless-stopped
    env_file:
      - src/app/.env
    environment:
      APP_ENV_FILE: /app/app/.env
      HOST: 0.0.0.0
      PORT: 8000
      POSTGRES_HOST: postgres_pr
      POSTGRES_PORT: 5432
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./src/app/.env:/app/app/.env:ro
    depends_on:
      postgres_pr:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["python", "main.py"]

  frontend:
    container_name: hackathon_mes_frontend
    build:
      context: spa
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  hackathon_SL_vol:
    driver: local
